ALTER TABLE Employees ALTER COLUMN Name NVARCHAR(50) NULL;
ALTER TABLE Employees ALTER COLUMN Surname NVARCHAR(50) NULL;
ALTER TABLE Employees ALTER COLUMN Phone NVARCHAR(50) NULL;
ALTER TABLE Employees ALTER COLUMN CompanyId INT NULL;
ALTER TABLE Employees ALTER COLUMN PassportId INT NULL;
ALTER TABLE Employees ALTER COLUMN DepartmentId INT NULL;

ALTER TABLE Companies ALTER COLUMN Name NVARCHAR(50) NULL;
ALTER TABLE Companies ALTER COLUMN Address NVARCHAR(60) NULL;

ALTER TABLE Departments ALTER COLUMN Name NVARCHAR(50) NULL;
ALTER TABLE Departments ALTER COLUMN Phone NVARCHAR(60) NULL;

ALTER TABLE Passports ALTER COLUMN Type NVARCHAR(50) NULL;
ALTER TABLE Passports ALTER COLUMN Number NVARCHAR(60) NULL;